### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by DougMaier** [DougMaier/codelab-html-intro#1]
Hey @icy-wolf, can you take a look at this? It's [hosted here](feeble-pain.surge.sh) and meets the following [project](http://lansingcodelab.com/lessons/html-intro/1) criteria:
- [x] Use at least one `h1` element.
- [x] Use at least one `a` element.
- [x] Use at least one `p` element.
- [x] Use at least one `img` element.
- [x] Use at least one `ul` element.
- [x] Use at least one `li` element.
- [x] When you paste the address of your website into [the W3C validator](https://validator.w3.org/), it returns no errors (warnings are OK).
- [x] This is the last time I'll mention it, but once again, your project should be on GitHub and hosted online (I recommend using surge again).

**Comment by icy-wolf** [comment]
:shipit:

**Comment by DougMaier** [comment]
I didn't see anything in your message.  Was there more to it?

**Comment by icy-wolf** [comment]
Good Afternoon Mr. Doug,

Once your project meets the project criteria, we send you a single "shipit" squirrel ( :shipit: ) to indicate the project is correct and you are good to go for that assignment. If we find your project does not match the criteria or has errors, we write back how to help with your errors or point out the criteria your project does not meet.

If you have any more questions, please let me or any of the other mentors know and I hope you are having a great day!

Thank you,
Nicole (icy-wolf)

**Comment by DougMaier** [comment]
Thanks Nicole, I didn't get a ship-it squirrel the first time.  Thanks for filling me in on the secret.
